config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end

  resources :bookmarks, only: [:create]

  resources :movies, only: [:index]
  resources :bookmarks, only: :destroy

  get "/rankings", to: "lists#rankings", as: :rankings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, presence: true, length: { minimum: 7 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true

  def self.most_rated
    List
    .joins(:reviews)
    .group('lists.id')
    .order('AVG(reviews.rating) DESC')
    .limit(10)
  end

  def average_rating
    ratings = []
    self.reviews.each do |review|
      ratings << review.rating
    end
    ratings.sum / self.reviews.size
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_title,
    against: [ :title],
    using: {
      tsearch: { prefix: true }
    }

  def self.top_5_rated
    order(rating: :desc).take(5)
  end

  def self.most_added
    # most added to lists bookmark
    Movie
    .joins(:bookmarks)
    .group('movies.id')
    .order('COUNT(bookmarks.movie_id) DESC')
    .limit(10)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @bookmark = Bookmark.new(bookmark_params)
    if params[:list_id]
      @list = List.find(params[:list_id])
      @bookmark.list = @list
    end
    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to list_path(@bookmark.list) }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            'bookmark_form',
            partial: 'bookmarks/modal',
            locals: { bookmark: @bookmark, list: @list }
          )
        end
        format.html { render template: 'bookmarks/modal', status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
require 'open-uri'

class ListsController < ApplicationController
  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @movies_list = @list.bookmarks.order(created_at: :desc)
    @bookmark = Bookmark.new
    @review = Review.new
  end

  # def new
  #   @list = List.new
  # end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :index
    end
  end

  def rankings
    @top_5_movies = Movie.top_5_rated
    @most_added_movies = Movie.most_added
    @most_rated_lists = List.most_rated
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
    @bookmark = Bookmark.new
    if params[:query].present?
      @movies = @movies.search_by_title(params[:query])
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @list = List.find(params[:list_id])
    @review.list = @list
    respond_to do |format|
      if @review.save
        format.turbo_stream do
          render turbo_stream: turbo_stream.prepend(
            'reviews-list',
            partial: 'reviews/review_message',
            locals: { review: @review }
          )
        end
        format.turbo_stream do
         render turbo_stream: turbo_stream.replace(
            'reviews-form',
            partial: 'form',
            locals: { list: @list, review: Review.new }
          )
        end
        format.html { render partial: 'review_message', locals: { review: @review }, status: :ok }
      else
        format.html { render partial: 'form', locals: { list: @list, review: @review }, status: :unprocessable_entity }
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/_modal.html.erb
<div class="modal-body" id='bookmark_form'>
  <%= turbo_frame_tag 'bookmark', target: '_top' do %>
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.association :movie, input_html: { class: 'select2' } %>
      <%= f.input :comment, as: :text %>
      <%= f.submit class: 'btn btn-blue' %>
    <% end %>    
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movie Night</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link href='https://unpkg.com/boxicons@2.1.4/dist/boxicons.js' rel='stylesheet'>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
      <%= yield %>
    <div id="flash">
      <%= render 'shared/flashes' %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/lists/_card.html.erb
<div class="movie-card">
  <div class="movie-image-container">
    <img src="<%= bookmark.movie.poster_url %>" alt="movie poster" class="movie-image">
    <span>
      <%= link_to bookmark_path(bookmark), method: "delete", class: "remove-mark" do %>
        <i class="far fa-minus-square"></i>
      <% end %>
    </span>
  </div>
  <div class="movie-info">
    <div class="title-wrapper">
      <h3><%= bookmark.movie.title %></h3>
    </div>
    <span class="rating" data-controller="color-rating" data-color-rating-target="rating"><%= bookmark.movie.rating %></span>
  </div>
  <div class="movie-comments">
    <i class="fas fa-quote-left"></i> <%= bookmark.comment %>
  </div>
  
  <div class="overview">
    <%= bookmark.movie.overview %>
  </div>
</div>

app/views/lists/_form.html.erb
<div class="form-styled">
  <h3>Create a new List</h3>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name, class: "form-input-small" %>
    <%= f.input :photo, as: :file, class: 'photo-button' %>
    <%= f.submit class: 'btn btn-blue' %>
  <% end %>
</div>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2104&q=80')">

  <div class="banner-text">
    <h1>Curated movie lists</h1>
    <h3>Find the perfect movie for your movie night</h3>
    <%= form_with url: movies_path, method: :get, class: "d-flex align-items-center" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control input-side",
            placeholder: "What movie are you looking for?"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-blue-slim btn-side" %>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="page-header-spaced">
    <h1>All lists</h1>
    <%= link_to '#list-form' do %>
      <button class="btn btn-blue">
        Create a new List
      </button>
    <% end %>
  </div>

  <div class="list-card-container" id="list-form">
    <% @lists.each do |list| %>
      <!-- <div data-aos="fade-up" data-aos-duration="2000"> -->
        <%= link_to list_path(list) do %>
          <div class="list-card" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : image_path('https://images.unsplash.com/photo-1542204165-65bf26472b9b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1334&q=80') %>)">
            <h3><%= list.name %></h3>
          </div>
        <% end %>
      <!-- </div> -->
    <% end %>
  </div>
  
  <div class="form-container">
    <%= render 'form' %>
  </div>
  
</div>

app/views/lists/rankings.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url('https://images.pexels.com/photos/11702566/pexels-photo-11702566.jpeg?auto=compress&cs=tinysrgb&w=800'); background-position: 60% 30%; height: 300px;" id="page-top">

  <div class="banner-text">
    <h1>Rankings</h1>
  </div>
</div>

<div class="row">
  <div class="col-12 col-md-9">
    <h2 class="text-center mt-4" id="top-5">Top 5 rated movies</h2>
    <div class="movies-list">
      <% @top_5_movies.each do |movie| %>
        <div class="movie-card">
          <div class="movie-image-container">
            <img src="<%= movie.poster_url %>" alt="movie poster" class="movie-image">
          </div>
          <div class="movie-info">
            <div class="title-wrapper">
              <h3><%= movie.title %></h3>
            </div>
            <span class="rating" data-controller="color-rating" data-color-rating-target="rating"><%= movie.rating %></span>
          </div>
          
          <div class="overview">
            <%= movie.overview %>
          </div>
        </div>
      <% end %>
    </div>

    <h2 class="text-center mt-4" id="most-added">Most added movies</h2>
    <div class="movies-list">
      <% @most_added_movies.each do |movie| %>
        <div class="movie-card">
          <div class="movie-image-container">
            <img src="<%= movie.poster_url %>" alt="movie poster" class="movie-image">
          </div>
          <div class="movie-info">
            <div class="title-wrapper">
              <h3><%= movie.title %></h3>
            </div>
            <span class="rating" data-controller="color-rating" data-color-rating-target="rating"><%= movie.rating %></span>
          </div>
          
          <div class="overview">
            <%= movie.overview %>
          </div>
        </div>
      <% end %>
    </div>
    
    <h2 class="text-center mt-4" id="best-rated-lists">Most Rated Lists</h2> <!-- movie-list-->

    <div class="list-card-container" id="list-form">
      <% @most_rated_lists.each do |list| %>
        <!-- <div data-aos="fade-up" data-aos-duration="2000"> -->
          <%= link_to list_path(list) do %>
            <div class="list-card" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.2)), url(<%= list.photo.attached? ? cl_image_path(list.photo.key) : image_path('https://images.unsplash.com/photo-1542204165-65bf26472b9b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1334&q=80') %>)">
              <h3><%= list.name %></h3>
              <h3><i class="fas fa-star"></i> <%= list.average_rating %></h3>
            </div>
          <% end %>
        <!-- </div> -->
      <% end %>
    </div>

  </div>

  <div class="col-md-3">
    <div class="menu-list">
      <div class="top-links">
        <a href="#top-5"><p>Top 5 movies</p></a>
        <a href="#most-added"><p>Most Added</p></a>
        <a href="#best-rated-lists"><p>Highest Rated Lists</p></a>
      </div>

      <div class="bottom-link">
        <a href="#page-top"><span class="d-flex align-items-center"><i class='bx bx-fade-up-hover bxs-up-arrow-circle bx-md'></i></span></a>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<% if @list.photo.attached? %>
  <div class="page-header-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, height: 400, width: 800, crop: :fill %>')">
    <div class="page-header-banner-content" >
      <h1><%= @list.name %></h1>
    </div>
  </div>
<% else %>
    <div class="page-header-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1542204165-65bf26472b9b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1334&q=80')">
    <div class="page-header-banner-content" >
      <h1><%= @list.name %></h1>
    </div>
  </div>
<% end %>

<div class="modal fade" id="bookmark-modal-form" tabindex="-1" aria-labelledby="bookmarkModalFormLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add a Movie to <%= @list.name %> list</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        <%= render 'bookmarks/modal' %>     
    </div>
  </div>
</div>

<!-- <div class="container"> -->
<div class="d-flex justify-content-end m-3">
  <div class="page-header">
    <button type="button" class="btn btn-blue mr-3" data-toggle="modal" data-target="#bookmark-modal-form">
        Bookmark a movie
    </button>
  </div>
</div>
<!-- </div>  -->


  <div class="row" data-controller="resetform">
    <div class="col-12 col-sm-12 col-md-9">
      <div class="movies-list">
        <% @movies_list.each do |bookmark| %>
          <%= render 'card', bookmark: bookmark %>
        <% end %>
      </div>
    </div>

    <div class="col-12 col-sm-12 col-md-3">
      <div class="reviews-container">
        <%= render 'reviews/form', list: @list, review: @review %>
        
          <div class="reviews-list">
            <%= turbo_frame_tag 'reviews-list' do %>
              <% if @list.reviews.empty? %>
                <p>Be the first to review this list!</p>
              <% end %>
              <% @list.reviews.order(created_at: :desc).each do |review| %>
                <%= render 'reviews/review_message', review: review %>
              <% end %>
            <% end %>
          </div>

      </div>
    </div>
  </div>
  

app/views/movies/_card.html.erb
<div data-controller="bookmark-form" class="movie-card-wrapper">
  <div class="movie-card">
    <div class="movie-image-container">
      <img src="<%= movie.poster_url %>" alt="movie poster" class="movie-image">
      <span data-action="click->bookmark-form#reveal">
        <i class="far fa-plus-square plus-mark"></i>
      </span>
    </div>
    <div class="movie-info">
      <div class="title-wrapper">
        <h3><%= movie.title %></h3>
      </div>
      <span class="rating" data-controller="color-rating" data-color-rating-target="rating"><%= movie.rating %></span>
    </div>
    
    <div class="overview">
      <%= movie.overview %>
    </div>
  </div> 
  <div class="d-none form-overlay" data-bookmark-form-target="form">
    <%= simple_form_for @bookmark do |f| %>
    <%= f.association :movie, as: :hidden, input_html: { value: movie.id } %>
    <%= f.association :list, input_html: { class: 'form-select' } %>
      <%= f.input :comment, as: :text %>
      <%= f.submit class: 'btn btn-blue' %>
    <% end %>
  </div>
</div>

app/views/movies/index.html.erb
<h1>Results</h1>

<div class="movies-list">
  <% @movies.each do |movie| %>
    <%= render "card", movie: movie %>
  <% end %>
</div>

app/views/reviews/_form.html.erb
<div class="reviews-form">
  <%= simple_form_for [list, review], data: { action: "turbo:submit-end->resetform#reset" } do |f| %>
    <span data-resetform-target='stars'>
      <%= f.input :rating, collection: (1..5).to_a, label: "Rate this movie list" %>
    </span>
    <%= f.input :content, label: 'Tell us what you think', as: :text, cols: 30, rows: 50 %>
    <%= f.submit "Publish", class: 'btn btn-blue-slim', data: { resetform_target: 'button' } %>
  <% end %>
</div>

app/views/reviews/_review_message.html.erb
<div id=<%= dom_id(review) %> class="review-content">
  <p><%= review.content %></p>
  <% if review.rating.nil? %>
    <% 5.times do %>
      <i class="far fa-star"></i>
    <% end %>
  <% else%>
    <% review.rating.times do %>
      <i class="fas fa-star"></i>
    <% end %>
    <% (5 - review.rating).times do %>
      <i class="far fa-star"></i>
    <% end %>
  <% end %>
</div>

app/views/reviews/new.html.erb
<!-- unused 

<div class="reviews-form">
  <%#= simple_form_for [@list, @review], data: { controller: "reset_form", action: 'turbo:submit-end->reset_form#reset' } do |f| %>
    <%#= f.input :rating, collection: (1..5).to_a, label: "Rate this movie list" %>
    <%#= f.input :content, label: 'Tell us what you think', as: :text, cols: 30, rows: 50 %>
    <%#= f.submit "Publish", class: 'btn btn-blue-slim' %>
  <% end %>
</div>

-->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  
  <div>
    This website is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark navbar-blue">
  <%= link_to root_path, class:"navbar-brand logo-white" do %>
    <div class="d-flex">
      <i class="fas fa-film"></i>
      <h3 class="ml-2">Movie Lists</h3>
    </div>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link text-white" href="/rankings">Rankings <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="/">All lists</a>
        </li>
      </ul>
  </div>
</nav>